'use strict';

// ============================================================
// CONTENT SCRIPT — https://replit.com/*
//
// WHY the hardcoded React-Aria IDs don't work:
//   IDs like `react-aria1080582148-:r1c:` are generated by React
//   Aria's counter at BUILD time. Every Replit deployment produces
//   different IDs. Hardcoding them is guaranteed to break.
//
// FIX: find the form by structure (type, name, role, placeholder)
//   which is stable across builds, then fall back to the known
//   snapshot IDs as a secondary attempt.
// ============================================================

// ── Known snapshot pairs (secondary attempt) ─────────────────
const SNAPSHOT_PAIRS = [
  { emailSel: '[id="username-:rv:"]',  btnSel: '[id="react-aria1080582148-:r1c:"]' },
  { emailSel: '[id="email-:r1o:"]',    btnSel: '[id="react-aria8519681457-:r25:"]' },
  { emailSel: '[id="username-:r0:"]',  btnSel: '[id="react-aria2175002955-:rd:"]'  },
  { emailSel: '[id="email-:r1b:"]',    btnSel: '[id="react-aria2637049068-:r1o:"]' },
];

// ── Stable selectors (primary attempt — build-independent) ────
const STABLE_EMAIL_SELS = [
  'input[name="identifier"]',       // Clerk standard
  'input[name="email"]',
  'input[name="username"]',
  'input[type="email"]',
  'input[autocomplete="email"]',
  'input[autocomplete="username"]',
  'input[placeholder*="email" i]',
  'input[placeholder*="username" i]',
  'input[placeholder*="Enter your" i]',
];

const STABLE_BTN_SELS = [
  'button[type="submit"]',
  'input[type="submit"]',
  'button[data-testid*="submit" i]',
  'button[aria-label*="continue" i]',
  'button[aria-label*="next" i]',
  'button[aria-label*="sign" i]',
];

// ── State ─────────────────────────────────────────────────────

let attached = false;

// ── Helpers ───────────────────────────────────────────────────

function send(type, extra = {}) {
  chrome.runtime.sendMessage({ type, ...extra }).catch(() => {});
}

function log(...args) {
  console.log('[VaultMail]', ...args);
}

// ── DOM debug dump — call once to see what's actually there ───

function dumpDOM() {
  const inputs = [...document.querySelectorAll('input')].map(el => ({
    id:          el.id          || '—',
    name:        el.name        || '—',
    type:        el.type        || '—',
    placeholder: el.placeholder || '—',
    visible:     el.offsetParent !== null,
  }));

  const buttons = [...document.querySelectorAll('button, input[type="submit"]')].map(el => ({
    id:    el.id              || '—',
    type:  el.type            || '—',
    label: el.getAttribute('aria-label') || '—',
    text:  el.textContent.trim().substring(0, 40) || '—',
  }));

  log('── DOM INPUTS ──', inputs);
  log('── DOM BUTTONS ──', buttons);
}

// ── Find email input (stable selectors) ──────────────────────

function findEmailInput() {
  // 1. Try stable selectors first
  for (const sel of STABLE_EMAIL_SELS) {
    try {
      const el = document.querySelector(sel);
      if (el && el.offsetParent !== null) { // visible check
        log('Email input found via stable selector:', sel, '→', el.id || el.name);
        return el;
      }
    } catch (_) {}
  }
  // 2. Try snapshot IDs
  for (const pair of SNAPSHOT_PAIRS) {
    try {
      const el = document.querySelector(pair.emailSel);
      if (el) {
        log('Email input found via snapshot selector:', pair.emailSel);
        return el;
      }
    } catch (_) {}
  }
  return null;
}

// ── Find submit button — scoped to same form/container ────────

function findSubmitBtn(emailInput) {
  // Prefer button inside the same form
  const form = emailInput?.closest('form');
  if (form) {
    for (const sel of STABLE_BTN_SELS) {
      const el = form.querySelector(sel);
      if (el) {
        log('Submit button found in form via:', sel, '→ id:', el.id || '—');
        return el;
      }
    }
    // Any button in the form
    const anyBtn = form.querySelector('button');
    if (anyBtn) {
      log('Submit button (any button in form):', anyBtn.textContent.trim());
      return anyBtn;
    }
  }

  // Walk up to find a container with a button
  let container = emailInput?.parentElement;
  for (let depth = 0; depth < 8 && container; depth++) {
    for (const sel of STABLE_BTN_SELS) {
      const el = container.querySelector(sel);
      if (el) {
        log('Submit button found in ancestor via:', sel);
        return el;
      }
    }
    container = container.parentElement;
  }

  // Snapshot IDs as last resort
  for (const pair of SNAPSHOT_PAIRS) {
    try {
      const el = document.querySelector(pair.btnSel);
      if (el) {
        log('Submit button found via snapshot:', pair.btnSel);
        return el;
      }
    } catch (_) {}
  }

  return null;
}

// ── Save email immediately on click ──────────────────────────

function saveEmail(email) {
  if (!email) { log('saveEmail called with empty value — skipping'); return; }
  log('Saving email:', email);
  chrome.storage.local.set({ currentActiveEmail: email }, () => {
    log('Storage updated — broadcasting ACTIVE_EMAIL_UPDATED');
    send('ACTIVE_EMAIL_UPDATED', { email });
  });
}

// ── Attach listeners once the form is found ───────────────────

function tryAttach() {
  if (attached) return true;

  const emailInput = findEmailInput();
  if (!emailInput) return false;

  const submitBtn = findSubmitBtn(emailInput);

  log('Form found! emailInput id:', emailInput.id || '—', 'name:', emailInput.name || '—');
  log('Submit button:', submitBtn ? (submitBtn.id || submitBtn.textContent.trim()) : 'NOT FOUND');

  if (!submitBtn) {
    // Attach to Enter key only
    emailInput.addEventListener('keydown', (e) => {
      if (e.key === 'Enter') saveEmail(emailInput.value.trim().toLowerCase());
    });
    attached = true;
    log('No submit button — listening for Enter only');
    return true;
  }

  attached = true;

  // mousedown: capture value before any blur event fires
  submitBtn.addEventListener('mousedown', () => {
    const v = emailInput.value.trim().toLowerCase();
    if (v) chrome.storage.local.set({ pendingEmail: v });
    log('mousedown pre-capture:', v || '(empty)');
  }, { capture: true });

  // click: definitive save
  submitBtn.addEventListener('click', () => {
    const v = emailInput.value.trim().toLowerCase();
    log('Button clicked — email value:', v || '(empty)');
    saveEmail(v);
  }, { capture: true });

  // Enter on input
  emailInput.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') {
      const v = emailInput.value.trim().toLowerCase();
      log('Enter pressed — email value:', v || '(empty)');
      saveEmail(v);
    }
  });

  // Form submit
  const form = emailInput.closest('form');
  if (form) {
    form.addEventListener('submit', () => {
      const v = emailInput.value.trim().toLowerCase();
      log('Form submit — email value:', v || '(empty)');
      saveEmail(v);
    }, { capture: true });
  }

  log('All listeners attached successfully');
  return true;
}

// ── MutationObserver ──────────────────────────────────────────

const observer = new MutationObserver(() => {
  if (tryAttach()) {
    observer.disconnect();
    log('Observer disconnected (form found)');
  }
});

observer.observe(document.documentElement, { childList: true, subtree: true });

// ── Re-attach on SPA navigation ───────────────────────────────

(function patchHistory() {
  const _push    = history.pushState.bind(history);
  const _replace = history.replaceState.bind(history);
  history.pushState    = (...a) => { _push(...a);    onNavigate(); };
  history.replaceState = (...a) => { _replace(...a); onNavigate(); };
})();

window.addEventListener('popstate', onNavigate);

function onNavigate() {
  attached = false;
  observer.observe(document.documentElement, { childList: true, subtree: true });
  setTimeout(() => {
    log('Navigation detected →', window.location.href);
    dumpDOM();
    tryAttach();
  }, 300);
}

// ── Init ──────────────────────────────────────────────────────

log('Content script loaded →', window.location.href);

// Dump DOM immediately + after short delay (React needs time to render)
dumpDOM();
setTimeout(() => {
  log('Delayed DOM check:');
  dumpDOM();
  tryAttach();
}, 1500);

tryAttach();
